version: "3.8"

services:
  backend:
    build: 
      context: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "8080:8080"